/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Mon Nov 30 14:42:32 2020
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 1480
#define M_7 100
#define M_11 1
#define M_12 15
#define M_16 1
#define M_17 15
#define M_28 3
#define M_34 1
#define M_35 15
#define M_37 1
#define M_38 15

// center of mass
#define L_1_6 -1.36
#define L_3_6 0.35

// inertia
#define IN_1_6 389.68
#define IN_5_6 2436.4
#define IN_9_6 2641.5
#define IN_1_12 0.1
#define IN_5_12 0.8
#define IN_9_12 0.1
#define IN_1_17 0.1
#define IN_5_17 0.8
#define IN_9_17 0.1
#define IN_1_35 0.1
#define IN_5_35 0.8
#define IN_9_35 0.1
#define IN_1_38 0.1
#define IN_5_38 0.8
#define IN_9_38 0.1

// body point
#define DPT_1_1 -0.02
#define DPT_2_1 -0.35
#define DPT_3_1 0.2
#define DPT_1_2 -0.02
#define DPT_2_2 0.35
#define DPT_3_2 0.2
#define DPT_2_3 0.35
#define DPT_2_4 -0.35
#define DPT_1_5 -2.78
#define DPT_2_5 -0.35
#define DPT_1_6 -2.78
#define DPT_2_6 -0.35
#define DPT_3_6 0.3
#define DPT_1_7 -2.78
#define DPT_2_7 0.35
#define DPT_1_8 -0.2
#define DPT_3_8 -0.05
#define DPT_1_9 -0.2
#define DPT_3_9 0.1
#define DPT_1_10 -2.78
#define DPT_2_10 0.35
#define DPT_3_10 0.3
#define DPT_2_11 0.35
#define DPT_3_11 0.3
#define DPT_1_12 -2.78
#define DPT_2_12 0.35
#define DPT_3_12 0.2
#define DPT_1_13 -2.78
#define DPT_2_13 -0.35
#define DPT_3_13 0.2
#define DPT_2_14 -0.35
#define DPT_3_14 0.3
#define DPT_1_15 -3.08
#define DPT_3_15 -0.05
#define DPT_1_16 -1.36
#define DPT_3_16 0.35
#define DPT_2_17 -0.4
#define DPT_1_18 0.1
#define DPT_2_18 -0.2
#define DPT_1_19 -0.1
#define DPT_3_19 -0.1
#define DPT_1_20 0.02
#define DPT_3_20 -0.2
#define DPT_3_21 -0.1
#define DPT_2_23 0.4
#define DPT_1_24 0.1
#define DPT_2_24 0.2
#define DPT_1_25 0.02
#define DPT_3_25 -0.2
#define DPT_3_26 -0.1
#define DPT_1_27 -0.1
#define DPT_3_27 -0.1
#define DPT_2_29 0.4
#define DPT_2_30 0.3
#define DPT_2_31 -0.4
#define DPT_2_32 -0.3
#define DPT_2_33 -0.4
#define DPT_2_34 -0.3
#define DPT_2_35 0.4
#define DPT_2_36 0.3
#define DPT_1_37 0.3
#define DPT_2_37 0.55
#define DPT_3_39 0.25
#define DPT_1_40 0.3
#define DPT_2_40 -0.55
#define DPT_3_41 0.25
#define DPT_2_42 -0.2
#define DPT_2_43 0.2
#define DPT_1_44 0.1
#define DPT_2_44 -0.54
#define DPT_1_45 0.1
#define DPT_2_45 0.54
#define DPT_2_46 0.4
#define DPT_1_47 0.1
#define DPT_2_47 0.2
#define DPT_3_48 -0.2
#define DPT_3_49 -0.1
#define DPT_2_51 -0.4
#define DPT_1_52 0.1
#define DPT_2_52 -0.2
#define DPT_3_53 -0.1
#define DPT_3_54 -0.2
#define DPT_1_57 0.3
#define DPT_2_57 0.55
#define DPT_1_58 0.3
#define DPT_2_58 -0.55
#define DPT_3_59 0.25
#define DPT_3_60 0.25

// ============================================================ //

# endif
