/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Fri Nov  8 11:38:33 2019
 * --------------------------------------------------------
 *
 */
#ifndef user_IO_h
#define user_IO_h


#include "mbs_user_interface.h"
// ============================================================ //


struct UserIO 
{
    double dummy; // empty variable for making the compiler happy! 
};

// ============================================================ //
 
# endif
