/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Mon Nov 30 14:42:32 2020
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define T1_chassis_id 1
#define T2_chassis_id 2
#define T3_chassis_id 3
#define R3_chassis_id 4
#define R1_chassis_id 5
#define R2_chassis_id 6
#define T1_weight_id 7
#define Joint_16_id 8
#define Joint_4_id 9
#define Joint_17_id 10
#define Joint_18_id 11
#define R2_wheel_ft_rt_id 12
#define Joint_6_id 13
#define Joint_5_id 14
#define Joint_8_id 15
#define Joint_9_id 16
#define R2_wheel_ft_lt_id 17
#define R1_bras_inf_av_g_1_id 18
#define R1_bras_inf_av_d_1_id 19
#define R1_bras_inf_ar_d_1_id 20
#define R1_bras_inf_ar_g_1_id 21
#define Joint_11_id 22
#define Joint_21_id 23
#define Joint_22_id 24
#define R2_def_bar_ft_id 25
#define Joint_24_id 26
#define Joint_25_id 27
#define T2_rack_id 28
#define Joint_0_id 29
#define Joint_1_id 30
#define Joint_2_id 31
#define Joint_3_id 32
#define Joint_31_id 33
#define Joint_38_id 34
#define R2_wheel_rr_lt_id 35
#define Joint_27_id 36
#define Joint_28_id 37
#define R2_wheel_rr_rt_id 38
#define Joint_32_id 39
#define R2_def_bar_rr_id 40
#define Joint_34_id 41
#define Joint_35_id 42
#define Joint_40_id 43
#define Joint_41_id 44


// body

#define Chassis_1_id 6
#define Weight_id 7
#define Bras_sup_av_d_1_id 8
#define Fusee_av_d_1_id 11
#define Roue_av_d_1_id 12
#define Bras_sup_av_g_1_id 13
#define Fusee_av_g_1_id 16
#define Roue_av_g_1_id 17
#define Bras_inf_av_g_1_id 18
#define Bras_inf_av_d_1_id 19
#define Bras_inf_ar_d_1_id 20
#define Bras_inf_ar_g_1_id 21
#define BAR_av_g_1_id 22
#define Bielle_av_g_id 24
#define BAR_av_d_1_id 25
#define Bielle_av_d_1_id 27
#define Bar_direction_1_id 28
#define Bielle_dir_d_1_id 30
#define Bielle_dir_g_1_id 32
#define Bras_sup_ar_g_1_id 33
#define Fusee_ar_g_1_id 34
#define Roue_ar_g_1_id 35
#define Bras_sup_ar_d_1_id 36
#define Fusee_ar_d_1_id 37
#define Roue_ar_d_1_id 38
#define BAR_ar_g_1_id 39
#define BAR_ar_d_1_id 40
#define Bielle_ar_d_1_id 42
#define Bielle_ar_g_1_id 44


// point

#define Chassis_1_to_bras_sup_av_d_1_id 1
#define Chassis_1_to_bras_sup_av_g_1_id 2
#define Chassis_1_Point_2_1_id 3
#define Chassis_1_Point_3_1_id 4
#define Chassis_1_Point_4_1_id 5
#define Chassis_1_Point_5_1_id 6
#define Chassis_1_Point_7_1_id 7
#define Chassis_1_Point_8_1_id 8
#define Chassis_1_Point_9_1_id 9
#define Chassis_1_Point_6_1_id 10
#define Chassis_1_Point_10_1_id 11
#define Chassis_1_to_bras_sup_ar_g_1_id 12
#define Chassis_1_to_bras_sup_ar_d_1_id 13
#define Chassis_1_Point_13_1_id 14
#define Chassis_1_Point_14_1_id 15
#define Chassis_1_CG_sensor_id 16
#define Bras_sup_av_d_1_L_bras_sup_av_d_1_id 17
#define Bras_sup_av_d_1_to_ball_id 18
#define Fusee_av_d_1_to_ball_dir_id 19
#define Fusee_av_d_1_to_ball_bras_inf_id 20
#define Fusee_av_d_1_to_roue_id 21
//#define Roue_av_d_1_origin_id 22
#define Bras_sup_av_g_1_L_bras_sup_av_g_1_id 23
#define Bras_sup_av_g_1_to_ball_id 24
#define Fusee_av_g_1_to_ball_bras_inf_id 25
#define Fusee_av_g_1_to_roue_id 26
#define Fusee_av_g_1_to_ball_dir_id 27
//#define Roue_av_g_1_origin_id 28
#define Bras_inf_av_g_1_Point_0_id 29
#define Bras_inf_av_g_1_Point_1_id 30
#define Bras_inf_av_d_1_Point_0_id 31
#define Bras_inf_av_d_1_Point_1_id 32
#define Bras_inf_ar_d_1_Point_0_id 33
#define Bras_inf_ar_d_1_Point_1_id 34
#define Bras_inf_ar_g_1_Point_0_id 35
#define Bras_inf_ar_g_1_Point_1_id 36
#define BAR_av_g_1_Point_0_id 37
#define BAR_av_g_1_Point_1_id 38
#define Bielle_av_g_Point_0_id 39
#define BAR_av_d_1_Point_0_id 40
#define Bielle_av_d_1_Point_0_id 41
#define Bar_direction_1_Point_0_id 42
#define Bar_direction_1_Point_1_id 43
#define Bielle_dir_d_1_Point_0_id 44
#define Bielle_dir_g_1_Point_0_id 45
#define Bras_sup_ar_g_1_L_bras_sup_ar_g_1_id 46
#define Bras_sup_ar_g_1_to_ball_id 47
#define Fusee_ar_g_1_to_ball_bras_inf_id 48
#define Fusee_ar_g_1_to_roue_id 49
//#define Roue_ar_g_1_origin_id 50
#define Bras_sup_ar_d_1_L_bras_sup_ar_d_1_id 51
#define Bras_sup_ar_d_1_to_ball_id 52
#define Fusee_ar_d_1_to_roue_id 53
#define Fusee_ar_d_1_to_ball_bras_inf_id 54
//#define Roue_ar_d_1_origin_id 55
#define BAR_ar_g_1_Point_0_id 56
#define BAR_ar_g_1_Point_1_id 57
#define BAR_ar_d_1_Point_0_id 58
#define Bielle_ar_d_1_Point_0_id 59
#define Bielle_ar_g_1_Point_0_id 60


// sensor

#define Sensor_chassis_id 1


// extforce

#define F_av_d_1_id 1
#define F_av_g_1_id 2
#define F_ar_g_1_id 3
#define F_ar_d_1_id 4


// links

#define Amortisseur_av_g_1_id 1
#define Amortisseur_av_d_1_id 2
#define Amortisseur_ar_d_1_id 3
#define Amortisseur_ar_g_1_id 4


// links 3D



// Rods



// ============================================================ //

# endif
